homebrew_taps:
  - caskroom/cask
  - caskroom/fonts
  - git-duet/tap
  - homebrew/php

homebrew_packages:
  - { name: ansible }
  - { name: autoconf }
  - { name: awscli }
  - { name: chromedriver }
  - { name: cmake }
  - { name: composer }
  - { name: coreutils }
  - { name: curl }
  - { name: curl, state: linked, install_options: force }
  - { name: docker }
  - { name: deployer }
  - { name: findutils }
  - { name: ghq }
  - { name: git }
  - { name: git-duet } # https://github.com/git-duet/homebrew-tap
  - { name: go }
  - { name: heroku }
  - { name: homebrew/php/php-cs-fixer }
  - { name: homebrew/php/php70-memcached }
  - { name: homebrew/php/phplint }
  - { name: httpie }
  - { name: icu4c }
  - { name: imagemagick }
  - { name: mysql }
  - { name: n }
  - { name: openssl }
  - { name: openssl, state: linked, install_options: force }
  - { name: peco }
  - { name: phpbrew }
  - { name: postgresql@9.6 }
  - { name: python }
  - { name: pyenv-virtualenv }
  - { name: readline }
  - { name: rbenv }
  - { name: screen }
  - { name: selenium-server-standalone }
  - { name: source-highlight }
  - { name: symfony-installer }
  - { name: the_silver_searcher }
  - { name: tree }
  - { name: wget }
  - { name: z }
  - { name: zsh }

homebrew_cask_packages:
  - { name: alfred }
  - { name: atom }
  - { name: clipy }
  - { name: dropbox }
  - { name: docker }
  - { name: firefox }
  - { name: font-ricty-diminished }
  - { name: font-source-han-code-jp }
  - { name: java }
  - { name: mysqlworkbench }
  - { name: ngrok }
  - { name: phpstorm }
  - { name: pycharm-ce }
  - { name: skype }
  - { name: vagrant }
  - { name: vagrant-manager }
  - { name: virtualbox }
  - { name: sketch }
  - { name: slack }
  - { name: google-chrome }
  - { name: google-drive }
  - { name: google-hangouts }
  - { name: google-japanese-ime }
  - { name: iterm2 }
  - { name: 1password }
